version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/face_recognition
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - static_data:/app/static
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=face_recognition
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  static_data: